# Generated by Django 5.0.6 on 2024-06-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyro1', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
