# Generated by Django 5.0.6 on 2024-06-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyro1', '0006_customuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=180)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
