# Generated by Django 5.0.6 on 2024-06-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyro1', '0007_user_delete_customuser_remove_comment_flagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='code_snippets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
