# Generated by Django 5.0.6 on 2024-06-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyro1', '0008_comment_code_snippets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='code_snippets',
        ),
    ]
