# Generated by Django 5.0.6 on 2024-06-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyro1', '0011_remove_user_is_admin_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
